name: Christchurch
favicon: null
layout_spectrum: 0.712302029831335
typography_spectrum: 0.9842470190487802
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.17356784734874964
  lightness: 0.61693652626127
  saturation: 0.17557161045260727
  rhythmicContrast: 0.3192678156774491
purpose: []
